layout_spectrum: 0.7781674
typography_spectrum: 0.05376344
color:
  saturation: 1
  brandStrength: 0.5245221
  lightness: 0.5752688
  rhythmicContrast: 0.811828
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Rattiram
